import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppHeader from "@/components/Layout/AppHeader";
import AppFooter from "@/components/Layout/basic/AppFooter";
import BasicLayout from "@/components/Layout/basic";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import ApploProvider from "@/provider/Apollo";

const inter = Inter({ subsets: ["latin"] });
const queryClient = new QueryClient();
export const metadata: Metadata = {
  title: "居家安全評估專家網 | Node.js專題",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ApploProvider>
        {/* <QueryClientProvider client={queryClient}> */}
        <body className={inter.className}>
          <BasicLayout>{children}</BasicLayout>
        </body>
      </ApploProvider>
      {/* </QueryClientProvider> */}
    </html>
  );
}
